-- Insert comprehensive UI texts for all pages
INSERT INTO public.ui_texts (key, value, description, category) VALUES
  -- Navigation
  ('nav.home', '首頁', 'Bottom navigation - Home', 'navigation'),
  ('nav.recharge', '儲值', 'Bottom navigation - Recharge', 'navigation'),
  ('nav.create', '發起', 'Bottom navigation - Create', 'navigation'),
  ('nav.mission', '任務', 'Bottom navigation - Mission', 'navigation'),
  ('nav.profile', '個人', 'Bottom navigation - Profile', 'navigation'),
  
  -- HomePage
  ('home.title', 'VoteChaos', 'App title', 'home'),
  ('home.subtitle', '投票混亂製造機', 'App subtitle', 'home'),
  ('home.tab.hot', '🔥 熱門', 'Hot topics tab', 'home'),
  ('home.tab.latest', '⚡ 最新', 'Latest topics tab', 'home'),
  ('home.tab.joined', '✅ 參與過', 'Joined topics tab', 'home'),
  ('home.empty.joined', '還沒有參與過的投票', 'Empty joined topics message', 'home'),
  ('home.action.start', '開始投票', 'Start voting button', 'home'),
  ('home.admob.banner', '📱 AdMob 廣告區域', 'AdMob banner placeholder', 'home'),
  ('home.admob.native', '📱 AdMob 中間廣告', 'AdMob native placeholder', 'home'),
  
  -- CreateTopicPage
  ('create.header', '發起主題', 'Create topic page header', 'create'),
  ('create.title.label', '主題標題', 'Topic title label', 'create'),
  ('create.title.placeholder', '輸入吸引人的標題...', 'Topic title placeholder', 'create'),
  ('create.options.label', '投票選項 (2-6個)', 'Vote options label', 'create'),
  ('create.options.add', '新增', 'Add option button', 'create'),
  ('create.options.placeholder', '選項', 'Option placeholder', 'create'),
  ('create.category.label', '話題分類', 'Category label', 'create'),
  ('create.category.placeholder', '選擇分類', 'Category placeholder', 'create'),
  ('create.category.food', '🍔 美食', 'Food category', 'create'),
  ('create.category.life', '🌟 生活', 'Life category', 'create'),
  ('create.category.tech', '💻 科技', 'Tech category', 'create'),
  ('create.category.sports', '⚽ 運動', 'Sports category', 'create'),
  ('create.category.entertainment', '🎬 娛樂', 'Entertainment category', 'create'),
  ('create.category.other', '🔮 其他', 'Other category', 'create'),
  ('create.tags.label', '話題標籤', 'Tags label', 'create'),
  ('create.tags.selected', '已選', 'Selected tags count', 'create'),
  ('create.tags.unit', '個', 'Tags count unit', 'create'),
  ('create.tags.max', '最多只能選擇 5 個標籤', 'Max tags error', 'create'),
  ('create.exposure.label', '曝光方案', 'Exposure plan label', 'create'),
  ('create.exposure.normal', '普通曝光', 'Normal exposure', 'create'),
  ('create.exposure.normal.desc', '標準推薦', 'Normal exposure description', 'create'),
  ('create.exposure.medium', '中等曝光', 'Medium exposure', 'create'),
  ('create.exposure.medium.desc', '優先推薦', 'Medium exposure description', 'create'),
  ('create.exposure.high', '高度曝光', 'High exposure', 'create'),
  ('create.exposure.high.desc', '置頂推薦', 'High exposure description', 'create'),
  ('create.duration.label', '投票天數', 'Duration label', 'create'),
  ('create.duration.days', '天', 'Days unit', 'create'),
  ('create.cost.exposure', '曝光方案', 'Exposure cost label', 'create'),
  ('create.cost.duration', '投票天數', 'Duration cost label', 'create'),
  ('create.cost.total', '總消耗代幣', 'Total cost label', 'create'),
  ('create.cost.remaining', '剩餘代幣', 'Remaining tokens label', 'create'),
  ('create.submit', '送出主題', 'Submit button', 'create'),
  ('create.submitting', '建立中...', 'Submitting state', 'create'),
  ('create.success', '主題已建立！', 'Success message', 'create'),
  ('create.success.desc', '消耗 {cost} 個代幣', 'Success description', 'create'),
  ('create.error.tokens', '代幣不足！', 'Insufficient tokens error', 'create'),
  ('create.error.login', '請先登入', 'Login required error', 'create'),
  
  -- ProfilePage
  ('profile.header', '個人資料', 'Profile page header', 'profile'),
  ('profile.tokens', '代幣', 'Tokens label', 'profile'),
  ('profile.stats.votes', '投票次數', 'Total votes stat', 'profile'),
  ('profile.stats.topics', '發起主題', 'Topics created stat', 'profile'),
  ('profile.history.title', '歷史紀錄', 'History section title', 'profile'),
  ('profile.history.votes', '投票紀錄', 'Vote history', 'profile'),
  ('profile.history.topics', '主題發起紀錄', 'Topic history', 'profile'),
  ('profile.history.tokens', '代幣使用紀錄', 'Token usage history', 'profile'),
  ('profile.settings.title', '設定', 'Settings section title', 'profile'),
  ('profile.settings.language', '語言與地區', 'Language setting', 'profile'),
  ('profile.settings.notifications', '通知設定', 'Notifications setting', 'profile'),
  ('profile.settings.terms', '使用者條款', 'Terms of service', 'profile'),
  ('profile.settings.privacy', '隱私權政策', 'Privacy policy', 'profile'),
  ('profile.settings.contact', '連絡我們', 'Contact us', 'profile'),
  ('profile.logout', '登出', 'Logout button', 'profile'),
  ('profile.version', 'VoteChaos v1.0.0', 'App version', 'profile'),
  ('profile.nameUpdated', '名稱已更新', 'Name updated message', 'profile'),
  ('profile.avatarUpdated', '頭像已更新', 'Avatar updated message', 'profile'),
  ('profile.settingsUpdated', '設定已更新', 'Settings updated message', 'profile'),
  
  -- MissionPage
  ('mission.header', '任務與獎勵', 'Mission page header', 'mission'),
  ('mission.subtitle', '完成任務賺代幣', 'Mission page subtitle', 'mission'),
  ('mission.ad.title', '觀看廣告', 'Watch ad title', 'mission'),
  ('mission.ad.subtitle', '輕鬆賺取代幣', 'Watch ad subtitle', 'mission'),
  ('mission.ad.button', '觀看 30 秒廣告', 'Watch ad button', 'mission'),
  ('mission.ad.loading', '載入中...', 'Loading ad message', 'mission'),
  ('mission.ad.success', '觀看廣告完成！', 'Ad watched success', 'mission'),
  ('mission.ad.reward', '獲得 {reward} 個代幣', 'Ad reward message', 'mission'),
  ('mission.list.title', '任務列表', 'Mission list title', 'mission'),
  ('mission.status.completed', '已完成', 'Completed status', 'mission'),
  ('mission.status.inProgress', '進行中', 'In progress status', 'mission'),
  ('mission.progress.complete', '完成', 'Progress complete', 'mission'),
  
  -- RechargePage
  ('recharge.header', '代幣儲值', 'Recharge page header', 'recharge'),
  ('recharge.subtitle', '購買代幣參與更多投票', 'Recharge page subtitle', 'recharge'),
  ('recharge.balance', '當前代幣餘額', 'Current balance label', 'recharge'),
  ('recharge.packages.title', '選擇儲值方案', 'Packages title', 'recharge'),
  ('recharge.package.popular', '最超值', 'Popular badge', 'recharge'),
  ('recharge.package.tokens', '代幣', 'Tokens label', 'recharge'),
  ('recharge.package.bonus', '贈送', 'Bonus label', 'recharge'),
  ('recharge.package.buy', '購買', 'Buy button', 'recharge'),
  ('recharge.package.processing', '處理中...', 'Processing state', 'recharge'),
  ('recharge.success', '購買成功！', 'Purchase success', 'recharge'),
  ('recharge.success.desc', '已獲得 {tokens} 代幣', 'Purchase success description', 'recharge'),
  ('recharge.info.title', '💡 儲值說明', 'Recharge info title', 'recharge'),
  ('recharge.info.1', '代幣可用於投票、發起主題等功能', 'Info point 1', 'recharge'),
  ('recharge.info.2', '儲值金額越高，贈送代幣越多', 'Info point 2', 'recharge'),
  ('recharge.info.3', '完成每日任務也可免費獲得代幣', 'Info point 3', 'recharge'),
  ('recharge.info.4', '代幣永久有效，不會過期', 'Info point 4', 'recharge'),
  ('recharge.iap.title', '📱 關於行動應用內購', 'IAP info title', 'recharge'),
  ('recharge.iap.desc', '如需整合 Google Play 或 App Store 內購功能，需要使用 Capacitor 將應用打包為原生行動應用。目前的網頁版使用模擬購買流程。', 'IAP info description', 'recharge'),
  
  -- VoteDetailPage
  ('vote.header', '投票詳情', 'Vote detail page header', 'vote'),
  ('vote.select', '選擇你的答案', 'Select answer label', 'vote'),
  ('vote.invest', '投入代幣', 'Invest tokens label', 'vote'),
  ('vote.deadline', '投票截止時間', 'Vote deadline label', 'vote'),
  ('vote.success', '成功投票 {amount} 個代幣！', 'Vote success message', 'vote'),
  ('vote.success.desc', '你的選擇已記錄', 'Vote success description', 'vote'),
  ('vote.error.select', '請先選擇一個選項', 'Select option error', 'vote'),
  ('vote.error.tokens', '代幣不足！', 'Insufficient tokens error', 'vote'),
  ('vote.error.login', '請先登入', 'Login required error', 'vote'),
  
  -- AuthPage
  ('auth.title', 'VoteChaos', 'Auth page title', 'auth'),
  ('auth.subtitle', '加入最有趣的投票社群', 'Auth page subtitle', 'auth'),
  ('auth.tab.login', '登入', 'Login tab', 'auth'),
  ('auth.tab.signup', '註冊', 'Signup tab', 'auth'),
  ('auth.social.google', '使用 Google 登入', 'Google login', 'auth'),
  ('auth.social.apple', '使用 Apple 登入', 'Apple login', 'auth'),
  ('auth.divider', '或使用電子郵件', 'Email divider', 'auth'),
  ('auth.email.label', '電子郵件', 'Email label', 'auth'),
  ('auth.email.placeholder', 'your@email.com', 'Email placeholder', 'auth'),
  ('auth.password.label', '密碼', 'Password label', 'auth'),
  ('auth.password.placeholder', '••••••••', 'Password placeholder', 'auth'),
  ('auth.password.requirements', '至少 8 個字元，含大小寫字母和數字', 'Password requirements', 'auth'),
  ('auth.password.hint', '密碼需包含: 大寫字母、小寫字母、數字 (8-72 字元)', 'Password hint', 'auth'),
  ('auth.confirm.label', '確認密碼', 'Confirm password label', 'auth'),
  ('auth.confirm.placeholder', '請再次輸入密碼', 'Confirm password placeholder', 'auth'),
  ('auth.login.button', '登入', 'Login button', 'auth'),
  ('auth.signup.button', '註冊', 'Signup button', 'auth'),
  ('auth.login.success', '登入成功！', 'Login success', 'auth'),
  ('auth.signup.success', '註冊成功！正在登入...', 'Signup success', 'auth'),
  ('auth.error.mismatch', '密碼不一致', 'Password mismatch error', 'auth'),
  ('auth.error.minLength', '密碼至少需要 8 個字元', 'Min length error', 'auth'),
  ('auth.error.maxLength', '密碼最多 72 個字元', 'Max length error', 'auth'),
  ('auth.error.uppercase', '密碼需包含至少一個大寫字母', 'Uppercase error', 'auth'),
  ('auth.error.lowercase', '密碼需包含至少一個小寫字母', 'Lowercase error', 'auth'),
  ('auth.error.number', '密碼需包含至少一個數字', 'Number error', 'auth'),
  ('auth.error.registered', '此電子郵件已被註冊', 'Already registered error', 'auth'),
  ('auth.error.password', '密碼不符合安全要求', 'Password requirements error', 'auth'),
  
  -- Common
  ('common.loading', '載入中...', 'Loading text', 'common'),
  ('common.error', '發生錯誤', 'Error message', 'common'),
  ('common.success', '成功', 'Success message', 'common'),
  ('common.confirm', '確認', 'Confirm button', 'common'),
  ('common.cancel', '取消', 'Cancel button', 'common'),
  ('common.save', '儲存', 'Save button', 'common'),
  ('common.delete', '刪除', 'Delete button', 'common'),
  ('common.edit', '編輯', 'Edit button', 'common'),
  ('common.back', '返回', 'Back button', 'common'),
  ('common.tokens', '代幣', 'Tokens label', 'common'),
  ('common.days', '天', 'Days unit', 'common'),
  ('common.updateFailed', '更新失敗', 'Update failed message', 'common'),
  ('common.checkInput', '請檢查輸入資料', 'Check input message', 'common')
ON CONFLICT (key) DO NOTHING;